server:
  port: 2333

lavalink:
  server:
    password: "youshallnotpass"  # Change this for security
    sources:
      youtube: true
      soundcloud: true
    bufferDurationMs: 400
    opusEncodingQuality: 10
    resamplingQuality: LOW

logging:
  level:
    root: INFO
